Dereference device with a defer call to prevent memory leaks
google/gousb pull request #98
Opened 2021-04-23 10:03 UTC by danielpaulus

This PR fixes the memory leak mentioned in #97 

`gousb.OpenDevices` currently only dereferences libusb device pointers when opening is unsuccessful or when the opener returns false. 
This can cause a memory leak that becomes mostly visible when using multiple libusb contexts in a long running application. 

The fix is to always call `c.libusb.dereference(dev)` so the device reference counter is decreased when OpenDevices is done. That is not a problem as libusb increases the reference counter internally on the `c.libusb.open(dev)` call and releases it when we call `c.libusb.close(dev)` again.

2021-04-23 10:45 UTC, danielpaulus commented
@googlebot I signed it!

2021-04-23 10:45 UTC, danielpaulus commented
> [![Coverage Status](https://camo.githubusercontent.com/61c2dc3580987c64bfae10ba66c25a30e95eeab26409a8e40fc80ae49486b350/68747470733a2f2f636f766572616c6c732e696f2f6275696c64732f33393037343835312f6261646765)](https://coveralls.io/builds/39074851)
> 
> Coverage increased (+0.1%) to 79.409% when pulling **[e40a201](https://github.com/google/gousb/commit/e40a20173bcdf105403b0f7607b468652154165a) on danielpaulus:fix-memleak-in-opendevices** into **[0eba1b1](https://github.com/google/gousb/commit/0eba1b126450dc6c62ded3542c825f645789a226) on google:master**.

wow I even increased code coverage ;-)

2021-04-26 12:14 UTC, zagrodzki requested changes
could you also update a comment in https://github.com/google/gousb/blob/master/libusb.go#L212? it is misleading now as it is, since it implies that all devices returned on the list will be "closed" (and so also opened) at some point, but this is not the case.

2021-04-26 12:14 UTC, zagrodzki commented on usb.go
>  		if opener(desc) {
please change this to:
if !opener(desc) {
  continue
}
and unindent the rest

2021-04-27 12:39 UTC, danielpaulus commented
> could you also update a comment in https://github.com/google/gousb/blob/master/libusb.go#L212? it is misleading now as it is, since it implies that all devices returned on the list will be "closed" (and so also opened) at some point, but this is not the case.

Done.
Should I also create a small unit test for OpenDevices while I am at it?

2021-04-27 13:20 UTC, zagrodzki approved these changes
> Should I also create a small unit test for OpenDevices while I am at it?

sure, if you want. You can do that in a separate PR perhaps, this one I think is good to go.

2021-04-27 13:20 UTC, zagrodzki commented on libusb.go
> +	// devices must be dereferenced by the caller to prevent memoryleaks
s/memoryleaks/memory leaks

2021-07-06 15:17 UTC, danielpaulus commented
hey @zagrodzki ,
is there anything missing on the PR? If not, when do you think you can release it? I would like to move away from using my private fork :-)

2021-07-09 13:23 UTC, zagrodzki commented
sorry, I assumed you will be able to merge yourself after my approval, but it seems this is not how GitHub flow works...

There is one comment left: typo in libusb.go (https://github.com/google/gousb/pull/98#discussion_r621199462)

2021-11-01 20:40 UTC, merged